baseURL = "https://poisotlab.github.io/AnalysisOfEcologicalNetworks/"
languageCode = "en-ca"
preserveTaxonomyNames = true

PygmentsCodeFences = false

[params]
  title = "Practical Analysis of Ecological Networks"
  subtitle = "BIO3043 / BIO6037"
  email = "timothee.poisot@umontreal.ca"

[permalinks]
  chapters = "/:section/:title/"

[markup.goldmark.renderer]
  unsafe= true

[menu]
  [[menu.main]]
    name = "Chapters"
    url = "/chapters/"
    weight = 1
  [[menu.main]]
    name = "Syllabus"
    url = "/syllabus/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3