name: Compile

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.2.0
      - name: Install packages
        run: julia --project -e 'import Pkg; Pkg.instantiate()'
      - name: Prepare output folder for notebooks
        run: mkdir -p dist/notebooks
      - name: Prepare output folder for static files
        run: mkdir -p dist/chapters
      - name: Run Weave
        run: julia --project builder.jl
      - name: Deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: "dist/"
          GH_PAT: ${{ secrets.ACCESS_TOKEN }}
