name: Compile

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.4.0
      
      - name: Install packages
        run: julia --project -e 'import Pkg; Pkg.instantiate()'
      
      - name: Run Weave
        run: julia --project builder.jl
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.68.3'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public