name: Compile

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: 1.2.0
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Install packages
        run: julia --project -e 'import Pkg; Pkg.instantiate()'
      - name: Prepare output folder
        run: mkdir -p dist/notebooks
      - name: Deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: "dist/"
          GH_PAT: ${{ secrets.ACCESS_TOKEN }}
